
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat_home
  longitude: !secret long_home
  # Configure country
  country: SE
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 6
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Enables the frontend
frontend:

# Enables the system_health API and system health info
system_health:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  #base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Discover some devices automatically
discovery:

# Simple service discovery platform
ssdp:

# Scan network for compatible devices
zeroconf:

# Text to speech
tts:
  - platform: google_translate

################################
# Enable use of helpers in GUI #
################################
input_boolean:
input_text:
input_button:
input_datetime:
input_number:
input_select:

##################################
# Logging and history components #
##################################
# Enables support for tracking state changes over time. Uses recorder component
history:
#  exclude:
#    domains:
#      - automation
#      - zwave
#      - switch
#      - device_tracker
#      - light
#    entities:
#      - group.all_switches
#      - group.all_devices
#      - sensor.ssl_cert_expiry
#      - sensor.yr_symbol
#      - sun.sun
#      - sensor.illumination_34ce00fb4f7c
#      - timer.kaffetimer

# View all events in a logbook. Uses recorder component
logbook:

# Enables support for tracking state changes over time.
recorder:
  # Delete events and states older than 1 week
  #purge_interval: 2
  purge_keep_days: 7

# Set severity level for log
logger:
  default: warning

#########################
# Location and tracking #
#########################
# Enables a map showing the location of tracked devices
map:

zone: !include zones.yaml

person:

#device_tracker:
#  - platform: netgear
#    #url: http://routerlogin.net:80
#    #host: !secret router_ip
#    #port: !secret router_port
#    #username: !secret router_username
#    password: !secret router_password
#    new_device_defaults:
#      track_new_devices: false

###########
# Weather #
###########
# Track the sun
sun:

##########
# Timers #
##########
# Timer for coffe maker, used in kaffetimer.yaml
#timer:
#  kaffetimer:
#    duration: '00:45:00'

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include_dir_merge_list scenes/
